### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by grantmcconnaughey** [epantry/django-sql-explorer#137]
Django 1.9a1 was released on PyPI, and there seems to be an incompatibility issues with django-sql-explorer. It looks like Django 1.9 removed the `FileWrapper` class, although I can't find any mention of that in the 1.9 release notes (they are a work on progress, however). Here's my Traceback:

```
Traceback (most recent call last):
  File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/explorer/admin.py", line 3, in <module>
    from explorer.actions import generate_report_action
  File "/Users/grant/.virtualenvs/my_app/lib/python2.7/site-packages/explorer/actions.py", line 5, in <module>
    from django.core.servers.basehttp import FileWrapper
ImportError: cannot import name FileWrapper
```

**Comment by grantmcconnaughey** [comment]
[Here's the commit](https://github.com/django/django/commit/bbe28496d32f76ca161f5c33787d6ad62267fcc6#diff-f6d1c75ec606389da5af6558bf57f171) where this was removed. Looks like it was actually just an alias to a class in the wsgiref package.

**Comment by bhargav3** [comment]
@grantmcconnaughey So what is the class name?
